// Sushi Model ------------------------------------------------------
// 'use strict';
module.exports = function (sequelize, DataTypes) {
  var Sushis = sequelize.define("Sushis", {
    // ID is generated by default
    sushi_name: DataTypes.STRING,
    devoured: DataTypes.BOOLEAN,
  });
  return Sushis;
}